config/routes.rb
Rails.application.routes.draw do

  get 'pages/career'

  get 'pages/help'

  get 'pages/developer'

  get 'pages/aboutus'

  get 'pages/terms'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
# #--------Routes for food-----------#
   get 'foods/index'
#   get 'foods/show'
#   get 'foods/new'
#   get 'foods/edit'
#   get 'foods/delete'


#main homepage route
root 'homepage#index'
	

match ':controller(/:action(/:id))', :via => [:get, :post]



  devise_for :users, controllers: {
        sessions: 'user/sessions',
        #registrations: 'user/registrations'
      }


 #resources :foods, only: [:index, :create]

 # # #--------Routes for food-----------#
 #  get 'foods/index'		 => 'foods#index'
 # get 'foods/new'		=> 'foods#new'
 #  post 'foods/create'	=> 'foods#create'
 #  patch 'foods/update'	=> 'foods#update'
 #  get 'foods/show'		=> 'foods#show'
 #  get 'foods/edit'		=> 'foods#edit'
 #  get 'foods/delete'		=> 'foods#destroy'
 #  get 'foods/create'		=> 'foods#create'



 #--------Routes for Restaurant-----------#
# get 'restaurants/index' 			=> 'restaurant#index'
# get 'restaurants/new' 				=> 'restaurant#new'
# post 'restaurants/create'			=> 'restaurant#create'
# patch 'restaurants/update'			=> 'restaurant#update'
# get 'restaurants/show'		=> 'restaurant#show'
# get 'restaurants/edit'		=> 'restaurant#edit'
# get 'restaurants/delete'		=> 'restaurant#destroy'
# get 'restaurants/create'		=> 'restaurant#create'
# get 'restaurants/:id'			=> 'restaurants#index'

end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :restaurants

	#scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_one :profile

         accepts_nested_attributes_for :profile

 
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  
  #For user profile
  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
    params.require(:user).permit(:email, :password, profile_attributes: [:first_name, :last_name, :username, :email, :phone, :delivery_address])
  end
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  
  def index
    @search = Food.search(params[:q])
    @food = @search.result
  end

  def show
    @food = Food.find(params[:id])
  end

  private

  def food_params
    params.require(:food).permit(:name, :description)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	layout 'home_layout'

	def index
		 @search = Food.search(params[:q])
    	@food = @search.result
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def career
  end

  def help
  end

  def developer
  end

  def aboutus
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="food_index">
	<h2> List of Foods</h2>

	 <table id = "foods">
	 	<% @food.each do |food| %>
	 		<tr>
	 			<td><%= food.name %></td>
	
	 		</tr>
	 	<% end %>
	 </table>
</div>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/homepage/index.html.erb
<div class="_background">
  <%= video_tag('cooking.mp4',poster:'background_01.svg', controls:false, autoplay:true, loop:true, autobuffer: true, muted:true) %>
</div>
<div class="_bg_overlay"></div>
<!--<div class="_background">-->
  <!--<%= image_tag('background_01.svg') %>-->
<!--</div>-->

<div class="_home_content">
  <div class="_logo">
    <%= image_tag('msosi-logo.svg', height: 100) %>
  </div>
  <div class="_search">
  
  <%= search_form_for @search, url: foods_index_path do |f| %>

       <%= f.text_field :name_cont %>
      <div class="action">
      <%= f.submit "Search" %> </div>
     <% end %>



    <!-- <form method="get" action="">
      <label><a href="#"> <%= image_tag('search-icon.svg', height: 15) %></a></label>
      <input type="text" placeholder="Restaurant Name/Food ...">
      <div class="styled-select">
        <select>
          <option>Restaurant</option>
          <option>Dish</option>
        </select>
      </div>
    </form> -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Msosi</title>
  <%= favicon_link_tag 'facion.'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Msosi Food</title>
  <%= favicon_link_tag 'favicon.png'%>
	<%= stylesheet_link_tag    'homepage', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
<nav>
	<div class="_logo">
    <a href="#"><%= image_tag('Msosi-Full.svg', height: 20) %></a>
  </div>
  <div class="_profile_tray">
    <div class="_profile">
      <!-- <a href="new_user_session_path"><%= image_tag('Profile-Icon.svg', height: 20) %></a> -->
      <%= link_to( image_tag('Profile-Icon.svg', height: 20), new_user_session_path ) %>
    </div>
    <div class="_tray">
      <a href="#"><%= image_tag('Tray-Icon.svg') %> Tray</a>
    </div>
  </div>
</nav>
<section>
	<%= yield %>
</section>
	
	<footer>

		<div class="_links">
      <div class="_social">
        <a href="#" ><%= image_tag('Twitter.svg', height: 20) %></a>
        <a href="#" ><%= image_tag('Facebook.svg', height: 20) %></a>
        <a href="#" ><%= image_tag('Linked In.svg', height: 20) %></a>
      </div>
      <div class="_stores">
        <a href="#" ><%= image_tag('AppStore.svg', height: 20) %></a>
        <a href="#" ><%= image_tag('GooglePlay.svg', height: 20) %></a>
      </div>
			<div class="top_links">
				<ul>
					<li><%= link_to 'CAREERS', pages_career_path %></li>
          <li><%= link_to 'HELP', pages_help_path %></li>
          <li><%= link_to 'DEVELOPER', pages_developer_path %></li>
          <li><%= link_to 'ABOUT US', pages_aboutus_path %></li>
				</ul>
			</div>

			<div class="bottom_links">
        <%= link_to 'TERMS AND CONDITIONS', pages_terms_path %>
			</div>
		</div>
	</footer>
</body>
</html>

app/views/pages/aboutus.html.erb
<h1>Pages#aboutus</h1>
<p>Find me in app/views/pages/aboutus.html.erb</p>

app/views/pages/career.html.erb
<h1>Pages#career</h1>
<p>Find me in app/views/pages/career.html.erb</p>

app/views/pages/developer.html.erb
<h1>Pages#developer</h1>
<p>Find me in app/views/pages/developer.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>